In [1]:
#1
import pandas as pd
import numpy as np



# Create a DataFrame with your data
data = {
    'age': ['<=30', '<=30', '31…40', '>40', '>40', '>40', '31…40', '<=30', '<=30', '>40', '<=30', '31…40', '31…40', '>40'],
    'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
    'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
    'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
    'buys_computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}



df = pd.DataFrame(data)






In [2]:
df

age  income student credit_rating buys_computer
0    <=30    high      no          fair            no
1    <=30    high      no     excellent            no
2   31…40    high      no          fair           yes
3     >40  medium      no          fair           yes
4     >40     low     yes          fair           yes
5     >40     low     yes     excellent            no
6   31…40     low     yes     excellent           yes
7    <=30  medium      no          fair            no
8    <=30     low     yes          fair           yes
9     >40  medium     yes          fair           yes
10   <=30  medium     yes     excellent           yes
11  31…40  medium      no     excellent           yes
12  31…40    high     yes          fair           yes
13    >40  medium      no     excellent            no

In [7]:
#1
# Calculate the total number of instances
total = len(df)

# Calculate the number of instances for each class
buy_yes = len(df[df['buys_computer'] == 'yes'])
buy_no = len(df[df['buys_computer'] == 'no'])

# Calculate the prior probabilities for each class
p_buy_yes = buy_yes / total
p_buy_no = buy_no / total

# Print the results
print(f'The prior probability of buying a computer is {p_buy_yes:.2f}')
print(f'The prior probability of not buying a computer is {p_buy_no:.2f}')


The prior probability of buying a computer is 0.64
The prior probability of not buying a computer is 0.36


In [6]:
#2
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.neighbors import KernelDensity

# Create a DataFrame with your data
data = {
    'age': ['<=30', '<=30', '31…40', '>40', '>40', '>40', '31…40', '<=30', '<=30', '>40', '<=30', '31…40', '31…40', '>40'],
    'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
    'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
    'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
    'buys_computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}

df = pd.DataFrame(data)

# Encode categorical features into numerical values
encoder = OrdinalEncoder()
encoded_data = encoder.fit_transform(df.drop('buys_computer', axis=1))

encoded_df = pd.DataFrame(encoded_data, columns=df.columns[:-1])

# Calculate class conditional densities for each feature with respect to 'buys_computer'
def calculate_class_conditional_density(feature, target_class):
    classes = df[target_class].unique()
    densities = {}
    for cls in classes:
        subset = encoded_df[df[target_class] == cls][feature]
        kde = KernelDensity(bandwidth=0.5)  # Adjust bandwidth as needed
        kde.fit(subset.to_numpy().reshape(-1, 1))  # Reshape for single feature
        unique_values = encoded_df[feature].unique()
        densities[cls] = {val: float(kde.score_samples([[val]])[0]) for val in unique_values}
    return densities

# Calculate class-conditional densities for each feature
features = ['age', 'income', 'student', 'credit_rating']
target_class = 'buys_computer'

for feature in features:
    print(f"Class-conditional densities for '{feature}' with respect to '{target_class}':")
    densities = calculate_class_conditional_density(feature, target_class)
    for cls, values in densities.items():
        print(f"Class '{cls}':")
        for val, density in values.items():
            print(f"Value '{val}': Density - {density}")
        print()
    print()


Class-conditional densities for 'age' with respect to 'buys_computer':
Class 'no':
Value '1.0': Density - -0.6502342349931015
Value '0.0': Density - -2.7349658388377964
Value '2.0': Density - -0.957261216228449

Class 'yes':
Value '1.0': Density - -1.3421104921803084
Value '0.0': Density - -0.9710094504808073
Value '2.0': Density - -1.2376107163256314


Class-conditional densities for 'income' with respect to 'buys_computer':
Class 'no':
Value '0.0': Density - -1.0762914373875292
Value '2.0': Density - -1.0762914373875296
Value '1.0': Density - -1.4025763620870362

Class 'yes':
Value '0.0': Density - -1.5444903278436755
Value '2.0': Density - -0.9398950903630245
Value '1.0': Density - -1.0848588750909527


Class-conditional densities for 'student' with respect to 'buys_computer':
Class 'no':
Value '0.0': Density - -0.41566085567348554
Value '1.0': Density - -1.4025763620870362

Class 'yes':
Value '0.0': Density - -1.0848588750909527
Value '1.0': Density - -0.565779965633324


Class-con

In [9]:
# Calculate the number of instances for buys_computer = 'yes'
buy_yes = len(df[df['buys_computer'] == 'yes'])

# Calculate the frequency of each age category for buys_computer = 'yes'
age_yes = df[df['buys_computer'] == 'yes']['age'].value_counts()

# Calculate the probability of each age category for buys_computer = 'yes'
p_age_yes = age_yes / buy_yes

# Print the results
print(f'The class conditional density for age given buys_computer = "yes" is:\n{p_age_yes}')
# Calculate the number of instances for buys_computer = 'no'
buy_no = len(df[df['buys_computer'] == 'no'])

# Calculate the frequency of each income category for buys_computer = 'no'
income_no = df[df['buys_computer'] == 'no']['income'].value_counts()

# Calculate the probability of each income category for buys_computer = 'no'
p_income_no = income_no / buy_no

# Print the results
print(f'The class conditional density for income given buys_computer = "no" is:\n{p_income_no}')
# Calculate the number of instances for buys_computer = 'no'
buy_no = len(df[df['buys_computer'] == 'no'])

# Calculate the frequency of each income category for buys_computer = 'no'
income_no = df[df['buys_computer'] == 'no']['income'].value_counts()

# Add one to the frequency of each income category
income_no_smooth = income_no + 1

# Calculate the smoothed probability of each income category for buys_computer = 'no'
p_income_no_smooth = income_no_smooth / (buy_no + 3)

# Print the results
print(f'The smoothed class conditional density for income given buys_computer = "no" is:\n{p_income_no_smooth}')



The class conditional density for age given buys_computer = "yes" is:
31…40    0.444444
>40      0.333333
<=30     0.222222
Name: age, dtype: float64
The class conditional density for income given buys_computer = "no" is:
high      0.4
medium    0.4
low       0.2
Name: income, dtype: float64
The smoothed class conditional density for income given buys_computer = "no" is:
high      0.375
medium    0.375
low       0.250
Name: income, dtype: float64


In [10]:
#3
from scipy.stats import chi2_contingency

# Create a contingency table for the given features
contingency_table = pd.crosstab(index=df['age'], columns=df['income']).values

# Perform Chi-squared test of independence for 'age' and 'income'
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'age' and 'income':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()

# Repeat the process for other pairs of features ('age' and 'student', 'age' and 'credit_rating', etc.)
# 'age' and 'student'
contingency_table = pd.crosstab(index=df['age'], columns=df['student']).values
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'age' and 'student':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()

# 'age' and 'credit_rating'
contingency_table = pd.crosstab(index=df['age'], columns=df['credit_rating']).values
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'age' and 'credit_rating':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()

# 'income' and 'student'
contingency_table = pd.crosstab(index=df['income'], columns=df['student']).values
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'income' and 'student':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()

# 'income' and 'credit_rating'
contingency_table = pd.crosstab(index=df['income'], columns=df['credit_rating']).values
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'income' and 'credit_rating':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()

# 'student' and 'credit_rating'
contingency_table = pd.crosstab(index=df['student'], columns=df['credit_rating']).values
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-squared test results for 'student' and 'credit_rating':")
print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of Freedom: {dof}")
print("Expected Frequencies:")
print(expected)
print()


Chi-squared test results for 'age' and 'income':
Chi2 Statistic: 3.3249999999999997
P-value: 0.5049810026322079
Degrees of Freedom: 4
Expected Frequencies:
[[1.14285714 1.14285714 1.71428571]
 [1.42857143 1.42857143 2.14285714]
 [1.42857143 1.42857143 2.14285714]]

Chi-squared test results for 'age' and 'student':
Chi2 Statistic: 0.4
P-value: 0.8187307530779818
Degrees of Freedom: 2
Expected Frequencies:
[[2.  2. ]
 [2.5 2.5]
 [2.5 2.5]]

Chi-squared test results for 'age' and 'credit_rating':
Chi2 Statistic: 0.11666666666666664
P-value: 0.9433354498734922
Degrees of Freedom: 2
Expected Frequencies:
[[1.71428571 2.28571429]
 [2.14285714 2.85714286]
 [2.14285714 2.85714286]]

Chi-squared test results for 'income' and 'student':
Chi2 Statistic: 5.666666666666666
P-value: 0.05881647164242991
Degrees of Freedom: 2
Expected Frequencies:
[[2. 2.]
 [2. 2.]
 [3. 3.]]

Chi-squared test results for 'income' and 'credit_rating':
Chi2 Statistic: 0.7291666666666666
P-value: 0.6944859597510076
Degre

In [15]:
#4
# Import the required modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Create a DataFrame with your data
data = {
    'age': ['<=30', '<=30', '31…40', '>40', '>40', '>40', '31…40', '<=30', '<=30', '>40', '<=30', '31…40', '31…40', '>40'],
    'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
    'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
    'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
    'buys_computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}

df = pd.DataFrame(data)

# Convert the categorical features into numerical values using label encoding
le = LabelEncoder()
df['age'] = le.fit_transform(df['age'])
df['income'] = le.fit_transform(df['income'])
df['student'] = le.fit_transform(df['student'])
df['credit_rating'] = le.fit_transform(df['credit_rating'])
df['buys_computer'] = le.fit_transform(df['buys_computer'])

# Split the data into training and testing sets using a 80-20 split
X = df.drop('buys_computer', axis=1) # feature matrix
y = df['buys_computer'] # response vector
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an instance of the GaussianNB class
model = GaussianNB()

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict the class labels for the testing data
y_pred = model.predict(X_test)

# Evaluate the performance of the model using some metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Print the results
print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1-score: {f1:.2f}')


Accuracy: 0.67
Precision: 0.67
Recall: 1.00
F1-score: 0.80
